image:
  repository: prom/prometheus
  tag: v2.53.0
  imageDigest: sha256:abcd1234ef567890... # required
  pullPolicy: Always

replicaCount: 1

resources:
  requests:
    cpu: "200m"
    memory: "256Mi"
  limits:
    cpu: "1"
    memory: "1Gi"
