image:
  repository: prom/alertmanager
  tag: v0.27.0
  imageDigest: ""   # inject at deploy
  pullPolicy: Always

replicaCount: 1

slack:
  existingSecret: alertmanager-secret
  secretKey: slack-webhook-url

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

securityContext:
  runAsUser: 1001
  runAsGroup: 1001
  fsGroup: 1001
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault
