apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: grafana-namespace-default-deny
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app: grafana
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: prometheus
      ports:
        - protocol: TCP
          port: 3000
