apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.admin.existingSecret }}
  namespace: monitoring
type: Opaque
stringData:
  {{ .Values.admin.userKey }}: "admin"
  {{ .Values.admin.passKey }}: "changeme"
