apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    alerting:
      alertmanagers:
        - static_configs:
            - targets: ["{{ .Values.alertmanager.serviceName }}:{{ .Values.alertmanager.servicePort }}"]

    rule_files:
      - /etc/prometheus/alert-rules.yml

    scrape_configs:
      - job_name: "mydev"
        metrics_path: /metrics
        scheme: http
        static_configs:
          - targets:
              - "mydev:3000"
