groups:
  - name: myapp-alerts
    interval: 30s
    rules:
      - alert: HighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) > 0.1
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "High 5xx Error Rate"
          description: "More than 0.1 5xx requests/sec over the last 5m."

      - alert: HighLatency
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 0.5
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High Latency (p95)"
          description: "95th percentile latency > 0.5s over last 5m."

      - alert: HighMemoryUsage
        expr: process_resident_memory_bytes / 1024 / 1024 > 200
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High Memory Usage"
          description: "App memory > 200MB for 5m."
