global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/alert.rules.yml

scrape_configs:
  - job_name: "mydev"
    metrics_path: /metrics
    scheme: https
    static_configs:
      - targets:
          - "mydev-staging.onrender.com"
          - "mydev-prod.onrender.com"
