apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager
  namespace: monitoring
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      labels:
        app: alertmanager
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
      containers:
        - name: alertmanager
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}@{{ .Values.image.imageDigest }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "--config.file=/etc/alertmanager/alertmanager.yml"
          resources: {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: alertmanager-config-vol
              mountPath: /etc/alertmanager
            - name: alertmanager-secret-vol
              mountPath: /etc/secrets/alertmanager
              readOnly: true
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: 9093
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /-/ready
              port: 9093
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: alertmanager-config-vol
          configMap:
            name: alertmanager-config
        - name: alertmanager-secret-vol
          secret:
            secretName: {{ .Values.slack.existingSecret }}
