apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-slack-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  slackWebhook: "" # <-- leave empty; inject via kubectl, not Helm
