apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-secret
  namespace: {{ .Values.namespace | default "monitoring" }}
  labels:
    app: alertmanager
type: Opaque
stringData:
  slack_webhook_url: {{ .Values.slack.webhook_url | quote }}
