name: CI/CD Pipeline

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build-test-scan:
    runs-on: ubuntu-latest
    steps:
      # Checkout repo
      - name: Checkout Code
        uses: actions/checkout@v3

      # Setup Node.js for tests + lint
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Install dependencies
      - name: Install Dependencies
        run: npm install

      # Run ESLint
      - name: Run ESLint
        run: npm run lint

      # Run Tests
      - name: Run Tests
        run: npm test

      # Dependency vulnerability check
      - name: Dependency Audit
        run: npm audit --audit-level=high

      # Build Docker image
      - name: Build Docker Image
        run: docker build -t myapp:${{ github.sha }} .

      # Scan Docker image with Trivy
      - name: Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: myapp:${{ github.sha }}

      # Push Docker image to GitHub Container Registry
      - name: Push to GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker tag myapp:${{ github.sha }} ghcr.io/${{ github.repository }}/myapp:${{ github.sha }}
          docker push ghcr.io/${{ github.repository }}/myapp:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-test-scan
    steps:
      - name: Deploy to Staging
        if: github.ref == 'refs/heads/develop'
        run: echo "🚀 Deploying from Docker image to staging..."

      - name: Deploy to Production
        if: github.ref == 'refs/heads/main'
        run: echo "🚀 Deploying from Docker image to production..."
