name: CI/CD Pipeline

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build-test-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Run Tests
        run: npm test -- --passWithNoTests

      - name: Dependency Audit
        run: npm audit --audit-level=high

      - name: Build Docker Image
        run: docker build -t mydev:${{ github.sha }} .

      - name: Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: mydev:${{ github.sha }}

      - name: Push to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
          IMAGE_NAME=docker.io/${{ secrets.DOCKERHUB_USERNAME }}/mydev
          docker tag mydev:${{ github.sha }} $IMAGE_NAME:${{ github.sha }}
          docker push $IMAGE_NAME:${{ github.sha }}
          docker tag mydev:${{ github.sha }} $IMAGE_NAME:latest
          docker push $IMAGE_NAME:latest

  deploy-staging:
    runs-on: ubuntu-latest
    needs: build-test-scan
    if: github.ref == 'refs/heads/develop'
    steps:
      - name: Trigger Render Staging Deploy
        run: |
          curl -X POST "https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys" \
            -H "Accept: application/json" \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}"

  deploy-prod:
    runs-on: ubuntu-latest
    needs: build-test-scan
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Trigger Render Production Deploy
        run: |
          curl -X POST "https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID_PROD }}/deploys" \
            -H "Accept: application/json" \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}"
